%this is a ERA algorithm Demo main function for Modal analysis
%By Chen yi, Jan. 24th,2004
%  State Key lab of Mechanical Transmission , Chonqqing University
%    chen_yi2000@sina.com
clear;
home
tic
close('all');
% open data files
disp('ERA Algorithm is working ...')
fid1=fopen('YData.txt','r');
fid2=fopen('sampling_frequencyHz.txt','r');
fid3=fopen('System_Eigenvalue.txt','w+');
fid4=fopen('System_Shape.txt','w+');
fid5=fopen('MAC.txt','w+');
fid6=fopen('MPC.txt','w+');
fid7=fopen('sampling_time.txt','r');
fid8=fopen('System_Modal_Parameters.txt','w+');
fid9=fopen('System_Mass_M.txt','w+');
fid10=fopen('Modal_Mass_M.txt','w+');

YData=fscanf(fid1,'%g');
sampling_frequencyHz=fscanf(fid2,'%g');
sampling_time=fscanf(fid7,'%g');
[Dynamic_Mass_M,Modal_Mass_M,System_Eigenvalue,System_Modal_damper_angular_freqency,System_Modal_Angular_Freqency,System_Modal_Damper_Ratio, System_Modal_Shape,System_recession_coefficient,MAC,MPC]=ERA(YData,sampling_frequencyHz);
figure(1)
stem(System_Eigenvalue,'o');
xlabel('Im. ');
ylabel('Re.');
title('System Eigenvalue List');
grid

figure(2)
stem(System_Modal_Shape,'^');
%plot(imag(System_Modal_Shape/max(System_Modal_Shape)));
xlabel('Re ');
ylabel('Im');
title('System Shape List');

grid on

figure(3)
stem(System_Modal_Shape/max(System_Modal_Shape),'ro');
xlabel('Re ');
ylabel('Im');
title('100%-System Shape List');

grid on
figure(4)
plot(System_Modal_Angular_Freqency/2/pi,'-.');
xlabel('No. ');
ylabel('Freqency f_i (Hz.)');
title('System Modal Freqency List');
grid on
figure(5)
plot(System_Modal_Angular_Freqency,'-.');
xlabel('No. ');
ylabel('Angular Freqency  /omega_i(rad/sec.)');
title('System Modal Angular Freqency List');
grid on
figure(6)
plot(System_Modal_Damper_Ratio,'-.');
xlabel('No. ');
ylabel('Damper Ratio');
title('System Modal Damper Ratio List');
grid on
figure(7)
plot(System_recession_coefficient);
xlabel('No.');
ylabel('System Recession Coefficient');
title('System Recession Coefficient Series');
grid on

figure(8)
plot(MAC,'-.');
xlabel('No.');
ylabel('MAC');
title('MAC Series');
grid on

figure(9)
plot(MPC,'-.');
xlabel('No.');
ylabel('MPC');
title('MPC Series');
grid on
figure(10)
stem(Dynamic_Mass_M,'o');
xlabel('No.');
ylabel('System Mass M');
grid on

figure(11)
stem(Modal_Mass_M,'o');
xlabel('No.');
ylabel('Modal Mass M');
grid on

%generate data files
fprintf(fid3,'%c','%   Generated By ERA Toolbox for Matlab ,By Chen yi, Chong Qing UnivercityBy Chen yi, Chong Qing Univercity');
fprintf(fid3,'\n');
fprintf(fid3,'%c','%   Jan.,24th,2004');
fprintf(fid3,'\n');
fprintf(fid3,'%c',' %   Chen_yi2000@sina.com');

fprintf(fid3,'\n');
fprintf(fid3,date);
fprintf(fid3,'\n');
fprintf(fid3,'\n');
fprintf(fid3,'%c','Order');
fprintf(fid3,'        ');
fprintf(fid3,'%c','Eigenvalue(Re.)');
fprintf(fid3,'        ');
fprintf(fid3,'%c','Eigenvalue(Im.)');
fprintf(fid3,'        ');
fprintf(fid3,'\n');
fprintf(fid3,'\n');
for loop_fid3=1:size(System_Eigenvalue,2)
    fprintf(fid3,'%g ',loop_fid3);
    fprintf(fid3,'         %g     ',real(System_Eigenvalue(loop_fid3)));
    fprintf(fid3,'         %g\n     ',imag(System_Eigenvalue(loop_fid3)));
 end   

fprintf(fid4,'%c','%   Generated By ERA Toolbox for Matlab ,By Chen yi, Chong Qing UnivercityBy Chen yi, Chong Qing Univercity');
fprintf(fid4,'\n');
fprintf(fid4,'%c','%   Jan.,24th,2004');
fprintf(fid4,'\n');
fprintf(fid4,'%c',' %   Chen_yi2000@sina.com');
fprintf(fid4,'\n');
fprintf(fid4,date);
fprintf(fid4,'\n');
fprintf(fid4,'\n');
fprintf(fid4,'%c','Order');
fprintf(fid4,'        ');
fprintf(fid4,'%c','System Modal Shape(Re)');
fprintf(fid4,'        ');
fprintf(fid4,'%c','System Modal Shape(Im)');
fprintf(fid4,'\n');
fprintf(fid4,'\n');
for loop_fid4=1:size(System_Modal_Shape,2)
    fprintf(fid4,'%g      ',loop_fid4);
    fprintf(fid4,'%g          ',real(System_Modal_Shape(loop_fid4)));
   fprintf(fid4,'%g\n       ',imag(System_Modal_Shape(loop_fid4)));
end
fprintf(fid5,'%c','%   Generated By ERA Toolbox for Matlab ,By Chen yi, Chong Qing UnivercityBy Chen yi, Chong Qing Univercity');
fprintf(fid5,'\n');
fprintf(fid5,'%c','%   Jan.,24th,2004');
fprintf(fid5,'\n');
fprintf(fid5,'%c',' %   Chen_yi2000@sina.com');
fprintf(fid5,'\n');
fprintf(fid5,date);
fprintf(fid5,'\n');
fprintf(fid5,'\n');
fprintf(fid5,'%g\n',MAC);

fprintf(fid6,'%c','%   Generated By ERA Toolbox for Matlab ,By Chen yi, Chong Qing UnivercityBy Chen yi, Chong Qing Univercity');
fprintf(fid6,'\n');
fprintf(fid6,'%c','%   Jan.,24th,2004');
fprintf(fid6,'\n');
fprintf(fid6,'%c',' %   Chen_yi2000@sina.com');
fprintf(fid6,'\n');
fprintf(fid6,date);
fprintf(fid6,'\n');
fprintf(fid6,'\n');
fprintf(fid6,'%g\n',MPC);

fprintf(fid8,'%c','%  Generated By ERA Toolbox for Matlab ,By Chen yi, Chong Qing Univercity');
fprintf(fid8,'\n');
fprintf(fid8,'%c','%   Jan.,24th,2004');
fprintf(fid8,'\n');
fprintf(fid8,'%c',' %   Chen_yi2000@sina.com');
fprintf(fid8,'\n');
fprintf(fid8,'\n');
fprintf(fid8,date);
fprintf(fid8,'\n');
fprintf(fid8,'\n');
fprintf(fid8,'%c','Order');
fprintf(fid8,'        ');
fprintf(fid8,'%c','Damper Ratio');
fprintf(fid8,'        ');
fprintf(fid8,'%c',' Modal Freqency(Hz.)');
fprintf(fid8,'        ');
%fprintf(fid3,'%c','Modal Angular Freqency(rad/s)');
%fprintf(fid3,'        ');
%fprintf(fid3,'%c','Modal damper angular freqency(rad/s)');
%fprintf(fid3,'        ');
fprintf(fid8,'\n');
fprintf(fid8,'\n');
for loop_fid8=1:size(System_Eigenvalue,2)
    fprintf(fid8,'%g ',loop_fid8);
    fprintf(fid8,'         %g    ',System_Modal_Damper_Ratio(loop_fid8));
    fprintf(fid8,'             %g\n     ',System_Modal_Angular_Freqency(loop_fid8)/2/pi);    
% fprintf(fid8,'              %g     ',System_Modal_Angular_Freqency(loop_fid3));    
% fprintf(fid8,'              %g\n     ',System_Modal_damper_angular_freqency(loop_fid3));    
end
fprintf(fid8,'\n');
fprintf(fid8,'\n');
fprintf(fid8,'%c','Sampling Freqency(Hz.)');
fprintf(fid8,'\n');
fprintf(fid8,'     %g     ',sampling_frequencyHz);

fprintf(fid9,'%c','%   Generated By ERA Toolbox for Matlab ,By Chen yi, Chong Qing UnivercityBy Chen yi, Chong Qing Univercity');
fprintf(fid9,'\n');
fprintf(fid9,'%c','%   Jan.,24th,2004');
fprintf(fid9,'\n');
fprintf(fid9,'%c',' %   Chen_yi2000@sina.com');
fprintf(fid9,'\n');
fprintf(fid9,date);
fprintf(fid9,'\n');
fprintf(fid9,'\n');
fprintf(fid9,'%c','System Mass M');
fprintf(fid9,'\n');
fprintf(fid9,'\n');
fprintf(fid9,'%g\n',Dynamic_Mass_M);

fprintf(fid10,'%c','%   Generated By ERA Toolbox for Matlab ,By Chen yi, Chong Qing UnivercityBy Chen yi, Chong Qing Univercity');
fprintf(fid10,'\n');
fprintf(fid10,'%c','%   Jan.,24th,2004');
fprintf(fid10,'\n');
fprintf(fid10,'%c',' %   Chen_yi2000@sina.com');
fprintf(fid10,'\n');
fprintf(fid10,date);
fprintf(fid10,'\n');
fprintf(fid10,'\n');
fprintf(fid10,'%c','Modal Mass M');
fprintf(fid10,'\n');
fprintf(fid10,'\n');
fprintf(fid10,'%g\n',Modal_Mass_M);

disp('ERA worked over, check out the result files.')
status=fclose('all');
toc




